### ISSUE TITLE
please publish version 1.1

### ISSUE THREAD

**Issue by nkconnor** [aws-actions/aws-codebuild-run-build#105]
https://github.com/aws-actions/aws-codebuild-run-build/compare/v1.0.5...master

there are inputs, including compute-type-override, that weren't included in the action.yml file at the time of the latest release

see also: #95

**Comment by mojca** [comment]
It seems to work with v1 (v1.0.6).
I assume that this could be closed?

**Comment by nkconnor** [comment]
If that is the case - yes.
