### ISSUE TITLE
Move to Node 16 and bump @actions/core package to v1.10.0 or greater.

### ISSUE THREAD

**Issue by samirkbee** [aws-actions/aws-codebuild-run-build#109]
Github has started the deprecation process of Node 12 for GitHub Actions. Github is showing warning for this action run. 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Also, 'set-output' and 'save-state' is deprecated and might get disabled by Github. @actions/core package needs to be bumped to v1.10.0 or greated and 'set-output' and 'save-state' needs to be removed if used anywhere.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by davydspotnana** [comment]
cc @subinataws @linghaoz

**Comment by davydspotnana** [comment]
Fixed in [`aws-actions/aws-codebuild-run-build@v1.0.8`](https://github.com/aws-actions/aws-codebuild-run-build/releases/tag/v1.0.8)

**Comment by davydspotnana** [comment]
can be closed 
cc @snowiow
