### ISSUE TITLE
Error: Unexpected key 'disableSourceOverride' found in params

### ISSUE THREAD

**Issue by FrancescaRodricks** [aws-actions/aws-codebuild-run-build#123]
This PR has broken builds https://github.com/aws-actions/aws-codebuild-run-build/pull/102 

And we get the following error when using `aws-actions/aws-codebuild-run-build@v1`

```
*****STARTING CODEBUILD*****
Error: Unexpected key 'disableSourceOverride' found in params
*****CODEBUILD COMPLETE*****
```

**Comment by taoyong-ty** [comment]
v1 release has already been rolled back, you should see recovery now

I am actively looking into the issue.

**Comment by taoyong-ty** [comment]
closing. let's track this issue in https://github.com/aws-actions/aws-codebuild-run-build/issues/122
