### ISSUE TITLE
Any way to fix event.json cannot found issue when I run `pnpm install` in CodeBuild?

### ISSUE THREAD

**Issue by roger-qi-chen** [aws-actions/aws-codebuild-run-build#127]
Hi guys, I got this error when I run `pnpm install` in CodeBuild. Seems that pnpm cannot found the GitHub event.json when install.
Is there any way to fix or ignore this?
Cheers!

113 | [Container] 2023/03/01 04:59:07 Running command pnpm install
114 | node:fs:585
115 | handleErrorFromBinding(ctx);
116 | ^
117 |  
118 | Error: ENOENT: no such file or directory, open '/home/runner/work/_temp/_github_workflow/event.json'
119 | at Object.openSync (node:fs:585:3)
120 | at Object.readFileSync (node:fs:453:35)
121 | at NodeFS.readFileSync (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:84834:28)
122 | at NodeFS.readJsonSync (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:84171:30)
123 | at ../node_modules/.pnpm/@yarnpkg+core@4.0.0-rc.39_typanion@3.12.1/node_modules/@yarnpkg/core/lib/Configuration.js (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:160610:117)
124 | at __require (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)
125 | at ../node_modules/.pnpm/@yarnpkg+core@4.0.0-rc.39_typanion@3.12.1/node_modules/@yarnpkg/core/lib/execUtils.js (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:161970:27)
126 | at __require (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:12:50)
127 | at ../node_modules/.pnpm/@yarnpkg+core@4.0.0-rc.39_typanion@3.12.1/node_modules/@yarnpkg/core/lib/index.js (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:174430:43)
128 | at __require (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:12:50) {
129 | errno: -2,
130 | syscall: 'open',
131 | code: 'ENOENT',
132 | path: '/home/runner/work/_temp/_github_workflow/event.json'
133 | }
134 |  
135 | [Container] 2023/03/01 04:59:07 Command did not exit successfully pnpm install exit status 1
136 | [Container] 2023/03/01 04:59:07 Phase complete: BUILD State: FAILED
137 | [Container] 2023/03/01 04:59:07 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: pnpm install. Reason: exit status 1

![image](https://user-images.githubusercontent.com/63796337/222054651-6413ce7c-aeeb-4f65-b040-6a781b9ba391.png)

**Comment by taoyong-ty** [comment]
I am not familiar with pnpm. could you check if this helps? https://github.com/pnpm/pnpm.github.io/issues/296

**Comment by roger-qi-chen** [comment]
> I am not familiar with pnpm. could you check if this helps? [pnpm/pnpm.github.io#296](https://github.com/pnpm/pnpm.github.io/issues/296)

**Comment by yiyang-ampup** [comment]
same issue.

I am converting the trigger from a Lambda function to a Github Action. Both are calling the exact same Codebuild project. But Lambda calling works, Github Action calling will result in this node:fs / event.json not found error.


The only difference seems to be Github Action > aws-codebuild-run-build@v1 is passing a lot of GITHUB_* variables. The particular file that is causing trouble seems to be `GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json`

Is there a way to NOT pass all the GITHUB_* variables?

**Comment by taoyong-ty** [comment]
Hi @yiyang-ampup, Thanks for the finding. 

This is expected behavior today. According to the [specs](https://github.com/aws-actions/aws-codebuild-run-build/blob/main/README.md), 

```
env-vars-for-codebuild (optional) : A comma-separated list of the names of environment variables that the action passes from GitHub Actions to CodeBuild.

The action passes these environment variables to CodeBuild along with any environment variables that have a github prefix.

This list is often the same or a subset of the list of environment variables that you define for GitHub actions in the env property.

Note: If you specify an environment variable with the same name as one defined in your CodeBuild project, the one defined here replaces the one in the CodeBuild project. For a list of CodeBuild environment variables, see
```

> Is there a way to NOT pass all the GITHUB_* variables?

No. But we can introduce a new `disable-github-env-vars` option, and update this [code block](https://github.com/aws-actions/aws-codebuild-run-build/blob/main/code-build.js#L255-L259) accordingly. We've made a [change](https://github.com/aws-actions/aws-codebuild-run-build/commit/431d0f22a796fd62408ba686b79c1b46c753e7bc) made for a similar requirement before. 


Your contributions via a. pull request will be much appreciated https://github.com/aws-actions/aws-codebuild-run-build/blob/main/CONTRIBUTING.md

**Comment by rstuhlmuller** [comment]
I am experiencing the same issue. When I run manually in the Codebuild console with the same sha, this error does not occur. I am not changing the buildspec or doing any manual changes. Commenting to follow this issue.
