### ISSUE TITLE
Can I make Github action not to wait for CodeBuild's completion?

### ISSUE THREAD

**Issue by muthudlg** [aws-actions/aws-codebuild-run-build#131]
Hi,

Thanks for implementing 'aws-actions/aws-codebuild-run-build@v1'. This is very useful.

My project has a requirement: Once the Codebuild job is triggered from Actions, the workflow should not wait for Codebuild job to complete.

Is there a way to force the Actions not to wait? Appreciate your help.

Thanks

**Comment by madebyherzblut** [comment]
You can call the CodeBuild API directly instead of using this action. See https://github.com/aws-actions/aws-codebuild-run-build/issues/51#issuecomment-792334571 for more info.

**Comment by muthudlg** [comment]
> You can call the CodeBuild API directly instead of using this action. See [#51 (comment)](https://github.com/aws-actions/aws-codebuild-run-build/issues/51#issuecomment-792334571) for more info.

thanks much @madebyherzblut  It worked :)

**Comment by muthudlg** [comment]
For those who are here for solution, below is the snippet I have used instead of  'aws-actions/aws-codebuild-run-build@v1':
`- name: Start CodeBuild run
      run: aws codebuild start-build --project-name MOSJ-TEST-AUTOMATION --environment-variables-override "[{\"name\":\"ACTION\",\"value\":\"create\"},{\"name\":\"BRANCH\",\"value\":\"${BITBUCKET_BRANCH}\"}]"
`
