### ISSUE TITLE
Support for Github concurrency to stop obsolete builds

### ISSUE THREAD

**Issue by pviolette3** [aws-actions/aws-codebuild-run-build#143]
One key feature of Github Actions is the ability to kill obsolete builds when an update to a PR is pushed, through concurrency control (https://docs.github.com/en/actions/using-jobs/using-concurrency#overview).

I believe the way this Action works is (per [docs](https://github.com/aws-actions/aws-codebuild-run-build#what-we-did)):
1. Github starts `aws-codebuild-run-build action` based on some event (e.g. PR created/updated/edited)
2. `aws-codebuild-run-build action` starts codebuild
3. `aws-codebuild-run-build action` polls codebuild for status
4. `aws-codebuild-run-build action` succeeds or fails based on the final status

I was curious how to accomplish canceling the codebuild job started in (2) if during the polling step (3), the Github action is cancelled.
Would it be possible to use the [expression functionality](https://docs.github.com/en/actions/learn-github-actions/expressions#example-of-cancelled), to [stop](https://docs.aws.amazon.com/codebuild/latest/APIReference/API_StopBuild.html) the `aws-codebuild-run-build-action`'s `aws-build-id` when the cancellation happens, for example?

Curious if anyone in the community has gotten something like this to work, or if there are any contributions that would be needed to the action to allow this type of thing to work?

Related issue: https://github.com/aws-actions/aws-codebuild-run-build/issues/134#issue-1751957902

(edit: [Action State](https://github.com/actions/toolkit/tree/main/packages/core#action-state) seems relevant. step (2) could store the build ID in Action State (which can potentially be removed in step (4) upon completion). Then, we can add a `cleanup` step after main that stops the build if the active build ID is present in the Action State.)

**Comment by taoyong-ty** [comment]
I've merged @pbrisbin change. Resolving.

**Comment by pviolette3** [comment]
Thank you for adding this feature @pbrisbin @taoyong-ty :)
