### ISSUE TITLE
Add support for `sourceTypeOverride` and `sourceLocationOverride`

### ISSUE THREAD

**Issue by yamao-latte** [aws-actions/aws-codebuild-run-build#164]
## Proposal: Add support for `sourceTypeOverride` and `sourceLocationOverride`

To enhance the usability of this Action and enable its integration with various source providers, such as GitHub Enterprise, we propose adding support for two new optional parameters:

1. `sourceTypeOverride`: This parameter allows users to override the source input type defined in the build project for the current build. By providing this option, users can specify alternative source types without modifying the underlying build project configuration. Valid values for this parameter would include:
   - `NO_SOURCE`
   - `CODECOMMIT`
   - `CODEPIPELINE`
   - `GITHUB`
   - `S3`
   - `BITBUCKET`
   - `GITHUB_ENTERPRISE`

2. `sourceLocationOverride`: This parameter enables users to specify a custom location that overrides the source location defined in the build project for the current build. By allowing users to provide an alternative source location, this feature offers flexibility in sourcing the build from different repositories or locations, depending on the specific requirements of each build.

The introduction of these parameters would greatly enhance the versatility of this Action, making it compatible with a wider range of source providers and enabling users to customize their build source settings on a per-build basis.

We believe that implementing this proposal would significantly improve the Action's adaptability and attract a larger user base, particularly those utilizing GitHub Enterprise or other source providers.

Please consider this proposal, and let us know your thoughts on how we can move forward with this enhancement.

**Comment by natanaelfiorilla-scopely** [comment]
+1

**Comment by taoyong-ty** [comment]
this is now supported
