### ISSUE TITLE
consider better name for env-passthrough input

### ISSUE THREAD

**Issue by mattsb42-aws** [aws-actions/aws-codebuild-run-build#17]
**NOTE: This might change between now and when we publish 1.0.0, but WILL NOT change after that.**

There's been some discussion about the naming of the `env-passthrough` input.

The purpose of this input value is to identify which environment variables in the GitHub Actions job runner environment will be passed in to the CodeBuild environment.

For example, if the GitHub Actions environment contains environment variables:

```
FOO="BAR"
BAZ="WOW"
COMMIT="1763481762348"
```

and `env-passthrough` is set to `FOO,COMMIT`

then the action will send the following environment variable overrides to the CodeBuild build:

```
FOO="BAR"
COMMIT="1763481762348"
```

Even though `BAZ` is set in the GitHub Actions environment, because it is not identified in `env-passthrough` it is not sent to CodeBuild.

If we can come up with a better name for this, I'm ok with changing this before `1.0.0`.

**Comment by mattsb42-aws** [comment]
proposed name: `env-codebuild`

**Comment by mattsb42-aws** [comment]
proposed name: `pass-env-to-codebuild`

I like this one because it identifies the action, subject, and target.

**Comment by mattsb42-aws** [comment]
proposed name: `envs-for-codebuild`

I like this one because it identifies the target and source, but differentiates `env` vs `envs` just enough to hint that they are different.

**Comment by robin-aws** [comment]
> proposed name: `envs-for-codebuild`
> 
> I like this one because it identifies the target and source, but differentiates `env` vs `envs` just enough to hint that they are different.

+1 on that hint. I'd actually suggest `env-vars-for-codebuild` to be even stronger about the hint.
