### ISSUE TITLE
Unable to See the build logs on Github UI

### ISSUE THREAD

**Issue by navaneeth-spotnana** [aws-actions/aws-codebuild-run-build#56]
The readme says:

> The action builds the CodeBuild project, collects the build logs, and prints them as they are written. The user experience is the same as it would be if the logic were executed in the GitHub Actions job runner.

Is this correct? Does the build log become available on the Github Action Run Interface? I don't see it.

![image](https://user-images.githubusercontent.com/57885431/95051665-3dee6380-070b-11eb-8308-1df3bdca5cff.png)

CodeBuild log:
```
...
9 | [Container] 2020/10/05 07:19:32 Registering with agent
10 | [Container] 2020/10/05 07:19:32 Phases found in YAML: 1
11 | [Container] 2020/10/05 07:19:32  BUILD: 1 commands
12 | [Container] 2020/10/05 07:19:33 Phase complete: DOWNLOAD_SOURCE State: SUCCEEDED
13 | [Container] 2020/10/05 07:19:33 Phase context status code:  Message:
14 | [Container] 2020/10/05 07:19:33 Entering phase INSTALL
15 | [Container] 2020/10/05 07:19:33 Phase complete: INSTALL State: SUCCEEDED
16 | [Container] 2020/10/05 07:19:33 Phase context status code:  Message:
17 | [Container] 2020/10/05 07:19:33 Entering phase PRE_BUILD
18 | [Container] 2020/10/05 07:19:33 Phase complete: PRE_BUILD State: SUCCEEDED
19 | [Container] 2020/10/05 07:19:33 Phase context status code:  Message:
20 | [Container] 2020/10/05 07:19:33 Entering phase BUILD
21 | [Container] 2020/10/05 07:19:33 Running command echo Hello World
22 | Hello World
23 |  
24 | [Container] 2020/10/05 07:19:33 Phase complete: BUILD State: SUCCEEDED
25 | [Container] 2020/10/05 07:19:33 Phase context status code:  Message:
26 | [Container] 2020/10/05 07:19:33 Entering phase POST_BUILD
```

**Comment by navaneeth-spotnana** [comment]
I think this is some permission issue, or something, because I tried it after a month, and it's working beautifully

**Comment by Mikequint94** [comment]
hey, can I ask you what your permissions look like?  
I am not about to see the build logs either in github UI.  The weird thing is, that it worked for a few weeks upon initial setup and then stopped working.
