### ISSUE TITLE
Unable to see build logs in GH on latest versions

### ISSUE THREAD

**Issue by Mikequint94** [aws-actions/aws-codebuild-run-build#67]
Using v1.0.3, the build logs were functional for a time showing up in the GH action but then they suddenly stopped appearing.  I checked and it is not a permissions issue because I can run an aws get-log-events just fine.  

The only solution I found was downgrading to v1.0.0 where the logs show up again, but the rate-limiting error is occuring.  (v1.0.1 and v1.0.2 also did not work).  Is there a better solution?

![Screen Shot 2021-06-14 at 2 41 26 PM](https://user-images.githubusercontent.com/28746506/121963221-aa037b80-cd1e-11eb-93c9-0098239b5f01.png)

Thank you!

**Comment by DrewCurd** [comment]
I have also started seeing this in our build logs.
Downgrading to v1.0.0 works only temporarily for us and is not quite as consistent.
