### ISSUE TITLE
Action for CodePipeline?

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [aws-actions/aws-codebuild-run-build#72]
Sorry for posting this here, I'm not sure where else to make this request. We use CodePipeline as part of our CI process (so we can also test out our pipeline infrastructure when we make changes). It would be great to have this same type of action but for CodePipeline instead (same basic functionality -- it will trigger the pipeline and wait for it to fail or complete successfully).

**Comment by mattsb42-aws** [comment]
The issue with triggering CodePipeline in a similar manner is that a pipeline can only be statically configured with a single source (generally a specific branch) and even if manually triggered, a you cannot override anything about a pipeline's operation.

So while it would be plausible to create something similar to `aws-codebuild-run-build` that runs a CodePipeline pipeline, it would only be able to run that pipeline using whatever source branch the pipeline is already configured to use.

**Comment by solarmosaic-kflorence** [comment]
@mattsb42-aws true, it is a bit more complicated. Currently we use a single CodeBuild job to update a source ZIP file in S3, which triggers the pipeline. That pattern would work well here, but I understand that probably not everyone uses that pattern.

**Comment by solarmosaic-kflorence** [comment]
I made https://github.com/solarmosaic/aws-codepipeline-execute
