### ISSUE TITLE
How to configure env variables as parameters ARN?

### ISSUE THREAD

**Issue by rmassoud** [aws-actions/aws-codebuild-run-build#90]
I want to configure env variables as ARN parameters to be grabbed from the parameter store in AWS? Is there a way to do this?

**Comment by taoyong-ty** [comment]
This is an example of specifying env vars https://github.com/jayheehee/docker-test/blob/3ba88ee5ed17548d2160dcd7f09ed6de30e32a70/.github/workflows/codebuild-workflow.yml#L32-L48
